/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      keyframes: {
        /* ----------------------------------------------
         * Generated by Animista on 2023-9-5 16:49:25
         * Licensed under FreeBSD License.
         * See http://animista.net/license for more info.
         * w: http://animista.net, t: @cssanimista
         * ---------------------------------------------- */
        scaleInCenter: {
          "0%": { transform: "scale(0)", opacity: "1" },
          "100%": {
            transform: "scale(1)",
            opacity: "1",
          },
        },
      },
      animation: {
        "scale-in": "scaleInCenter 2s both",
      },
    },
  },
  plugins: [],
};
